name: Update Schedule Live

on:
  schedule:
    - cron: "* * * * *" 
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run updater
        run: python jadwallipepoli.py

      - name: Configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Commit & Push changes
        run: |
          git add *.json
          # hanya commit jika ada perubahan
          git diff --cached --quiet || git commit -m "Auto update schedule [skip ci]"
          git push
