name: Update V-League Korea Schedule

on:
  schedule:
    - cron: "0 22 * * *" # jalan jam 05:00 WIB (GitHub pakai UTC)
  workflow_dispatch: # bisa run manual juga

jobs:
  update-schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update script
        run: python update_vleague.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add VLeagueKorea.json
          git commit -m "chore: auto-update V-League Korea schedule" || echo "No changes"
          git push
