name: Update Volleyballworld JSON

on:
  schedule:
    - cron: "*/5 * * * *"  # jalan tiap 5 menit
  workflow_dispatch:        # bisa dijalankan manual dari GitHub Actions tab

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python update_volleyballworld.py

      - name: Commit & Push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add volleyballworld.json
          git commit -m "Update volleyballworld.json [ci skip]" || echo "No changes to commit"
          git push
